# Generated by Django 4.1.7 on 2023-03-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_decription_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='adress',
            new_name='address',
        ),
    ]
