# Generated by Django 4.1.7 on 2023-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_adress_listing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=201),
        ),
    ]
